### ISSUE TITLE
TypeError: Unknown color 'bright_magenta'

### ISSUE THREAD

**Issue by NightMachinery** [jiaowoshabi/wkdict#5]
```
$ wkdict --version                                                                                               1
wkdict, version 0.1.0
$ wkdict malice                                                                                                  1

🔅 This application is powered by Wiktionary's API 🔅

Traceback (most recent call last):
  File "/Users/evar/anaconda/lib/python3.7/site-packages/click/termui.py", line 372, in style
    bits.append('\033[%dm' % (_ansi_colors.index(fg) + 30))
ValueError: tuple.index(x): x not in tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/evar/anaconda/bin/wkdict", line 10, in <module>
    sys.exit(main())
  File "/Users/evar/anaconda/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/evar/anaconda/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/evar/anaconda/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/evar/anaconda/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/evar/anaconda/lib/python3.7/site-packages/wkdict/command.py", line 19, in main
    ret = parseJSON(word, resjson, limit)
  File "/Users/evar/anaconda/lib/python3.7/site-packages/wkdict/wkdict.py", line 56, in parseJSON
    res += click.style('\t' + pron + '\n', fg='bright_magenta')
  File "/Users/evar/anaconda/lib/python3.7/site-packages/click/termui.py", line 374, in style
    raise TypeError('Unknown color %r' % fg)
TypeError: Unknown color 'bright_magenta'
```
(Just installed)

**Comment by NightMachinery** [comment]
So this is still unsolved ...

**Comment by wlmchen** [comment]
Because you are using ansii colors, bright_magenta isn't recognized. You could simply change it to a different color in line 56 of /Users/evar/anaconda/lib/python3.7/site-packages/wkdict/wkdict.py

ex.
before:  res += click.style('\t' + pron + '\n', fg='bright_magenta')
after:  res += click.style('\t' + pron + '\n', fg='blue')
