### ISSUE TITLE
Crash with word "fazer"

### ISSUE THREAD

**Issue by jorgesumle** [jiaowoshabi/wkdict#7]
I want to see the conjugations for Portuguese verbs. I tried this program, but it crashed when I searched for "fazer" (`wkdict fazer`):

```Traceback (most recent call last):
  File "/usr/local/bin/wkdict", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/wkdict/command.py", line 19, in main
    ret = parseJSON(word, resjson, limit)
  File "/usr/local/lib/python3.9/dist-packages/wkdict/wkdict.py", line 37, in parseJSON
    if len(table[0]["definitions"]) < 1:
IndexError: list index out of range
```

Also, I want to search only in Portuguese. Is there a way to specify that, like a `-l` command-line option?

**Comment by AshutoshGitMirror** [comment]
can confirm.
